# This workflow is to test a Makefile on an Ubuntu machine.
name: Makefile Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        # Add any necessary dependencies for your Makefile here
        # For example, if you need gcc and make:
        sudo apt-get install -y build-essential

    - name: Run make
      run: make
